### ISSUE TITLE
document.body doesn't exist. Modernizr hyphens test needs it. 

### ISSUE THREAD

**Issue by kenips** [russfrisch/modernizr-rails#22]
This happens only after upgrading to 2.6.2.2. Reverting back to 2.6.2.1 is fine.

Also in the log:

```
Uncaught TypeError: Cannot call method 'appendChild' of null 
```

So one of the builder option requires a special loading? It seems like it cannot support loading in head tags anymore?

**Comment by MicFin** [comment]
I am having this issue now in Modernizr 2.8.3. which appears similar to this thread 

```
'webkitAudioContext' is deprecated. Please use 'AudioContext' instead.
modernizr.min.js?body=1:5 document.body doesn't exist. Modernizr hyphens test needs it.
modernizr.min.js?body=1:6 Uncaught TypeError: Cannot read property 'appendChild' of null
```

**Comment by mltsy** [comment]
Might need to provide more context on how to reproduce the error, if you want to get help with this (unless other people are already having the same error, and know how to fix it).  You can also try posting your issue in https://github.com/Modernizr/Modernizr, if it's just an issue with Modernizr (this is just the gem to incorporate Modernizr as a rails asset)

**Comment by MicFin** [comment]
Thank you
